from . import account_move
from . import account_journal
from . import d394_rezumat1
from . import d394_rezumat2
from . import d394_op1
from . import d394_op2
from . import d394_lista
from . import d394_facturi
from . import d394_serie_facturi
from . import d394_template
from . import d394
from . import product_template
